#!/bin/bash -e

if [ -z "${ROUTER_INTERFACES}" ]; then
  echo "ERROR: No interfaces specified."
  exit 1
fi

BABELD_TABLE_ID=${BABELD_TABLE_ID:-21}
BABELD_TABLE_PRIO=${BABELD_TABLE_PRIO:-950}

# Configure routing policy
ip rule del from all lookup ${BABELD_TABLE_ID} || true 2>/dev/null
ip rule add from all lookup ${BABELD_TABLE_ID} prio ${BABELD_TABLE_PRIO}

# Configure babeld
BABELD_CONFIG=/etc/babeld.conf
echo "local-port 33123" > ${BABELD_CONFIG}
echo "export-table ${BABELD_TABLE_ID}" >> ${BABELD_CONFIG}
echo "import-table ${BABELD_TABLE_ID}" >> ${BABELD_CONFIG}

ifaces=""
for iface in ${ROUTER_INTERFACES}; do
  echo "interface ${iface} wired true" >> ${BABELD_CONFIG}
  echo "redistribute local if ${iface} allow" >> ${BABELD_CONFIG}
done

echo "redistribute local deny" >> ${BABELD_CONFIG}

exec /usr/sbin/babeld -c /etc/babeld.conf 2>&1

